module.exports = {
    compute: ["automaticRestartEnabled", 
            "enableUsageExport", 
            'instanceMaxCount', 
            'instancesMultiAz', 
            'autoscaleEnabled', 
            'instanceLevelSSHOnly',
            'instanceLeastPrivilege',
            'ipForwardingDisabled',
            'connectSerialPortsDisabled',
            'csekEncryptionEnabled', 
            'osLoginEnabled' , 
            'instancePublicAccess',
            'instanceDefaultServiceAccount', 
            'shieldedVmEnabled', 
            'instanceDeletionProtection',
            'autoscaleMinCpuUtilization',
            'instanceDesiredMachineTypes', 
            'instanceTemplateMachineTypes', 
            'diskMultiAz',
            'persistentDisksAutoDelete',
            'VMDisksCMKEncrypted',
            'instanceMaintenanceBehavior',
            'instancePreemptibility',
            'diskInUse',
            'osLogin2FAEnabled',
            'diskAutomaticBackupEnabled',
            'diskOldSnapshots',
            'frequentlyUsedSnapshots',
            'applicationConsistentSnapshots',
            'deprecatedImages',
            'enableUsageExport',
            'instanceGroupAutoHealing',
            'publicDiskImages',
            'snapshotLabelsAdded',
            'diskLabelsAdded',
            'imageLabelsAdded',
            'instanceLabelsAdded' ,
            'confidentialComputingEnabled',
            'imagesCMKEncrypted',
            'snapshotEncryption',
             'instanceNetworkExposure']      

}

